# Generated by Django 6.0.1 on 2026-01-09 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_quotation_quotationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='workdrive/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('QUOTATIONS', 'Quotations'), ('LEDGERS', 'Ledgers'), ('BANK_DOCUMENTS', 'Bank Documents'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
